### ISSUE TITLE
Errors are printed to stdout even with a custom error handler

### ISSUE THREAD

**Issue by arbue** [hongaar/bandersnatch#284]
Hi,

When an error is thrown by the command action the error is logged to stdout before the custom catch function of the program. 

This is the line which is printing the error before it is catched.
https://github.com/hongaar/bandersnatch/blob/a73115df1977c78c6a97e500bb9cec75674af704/src/program.ts#L222

I think it would be good if this could be turned off to be able to hide raw errors from the user. 
Especially the default errorHandler is also logging errors with console.error in the repl.ts 
https://github.com/hongaar/bandersnatch/blob/a73115df1977c78c6a97e500bb9cec75674af704/src/repl.ts#L24
Without a custom errorHandler the error is printed twice.

What do you think?

**Comment by hongaar** [comment]
Thanks for reporting this. I'll take a closer look soon because the first `console.error` should only be triggered on validation errors from yargs, but you're saying it also triggers on errors thrown from command action handlers.

**Comment by hongaar** [comment]
Diving into this, it looks like in `yargs` the behaviour of the `err` parameter to the `parse` callback changed and it is now populated with any errors thrown in the command action, not only validation errors. I'm having a look now and hope to push a fix soon.

**Comment by hongaar** [comment]
@arbue this behaviour has now been changed in #300 and released (see above). Thanks again for reporting this and by doing so improving this package 💪
