### ISSUE TITLE
Default to help if no command was provided

### ISSUE THREAD

**Issue by akii0008** [hongaar/bandersnatch#394]
Pretty much what it says in the title, it would be nice if there was an option to have the program output the generated help if there was nothing passed to either the REPL or argv.

**Comment by hongaar** [comment]
By default, bandersnatch will throw if there was a problem matching a command, some examples:

> - Not enough non-option arguments: got 0, need at least 1
> - Did you mean foo?
> - Unknown argument: unknown

You could show the help output in these cases by using something similar to this:

```js
app.catch((e) => {
  console.log(`${e.message}\n`)
  app.run('help')
})
```

I'm not sure if there's a way to detect _no arguments passed_ to the program with `yargs`. This would be required for this feature. Some additional scenario's which come to mind:

- No command provided
- No required arguments or invalid arguments provided
  - Detect nearest command/subcommand and show that help (e.g. `cmd sub --help`)

**Comment by akii0008** [comment]
Ah! I didn't know `program.run` was available. This makes things much easier. I'll go ahead and close this issue...
