### ISSUE TITLE
Sub Commands?

### ISSUE THREAD

**Issue by khill-fbmc** [hongaar/bandersnatch#396]
Before I start with my "issue" I want to thank you for all your work on this! It's fantastic and has really accelerated my CLI tool making. This is my second project using this library and I have found the need for sub-commands. I saw in the documentation that there is [support for sub commands](https://github.com/hongaar/bandersnatch#commandcommandcommand=)?

but when attempting this in vscode, I am getting no hints for `.command()`

I skimmed through the [command.ts](https://github.com/hongaar/bandersnatch/blob/main/src/command.ts) file to see if I could find it... No dice....

Suggestions?

**Comment by hongaar** [comment]
Hi @khill-fbmc, thanks for raising this issue. Looks like the behaviour described in the readme doesn't align with the code. The method either was never added or got removed somehow. I'll look into your PR.
