### ISSUE TITLE
Async `choices` for `.argument()`?

### ISSUE THREAD

**Issue by khill-fbmc** [hongaar/bandersnatch#397]
Is it possible to fetch a list of users let say, and have that displayed as the choices? I get that this would need to be typed, by my own interface perhaps, but would make it easy do work based on the results of a fs or api call.

**Comment by hongaar** [comment]
> [Oh but I think it does](https://github.com/yargs/yargs/blob/main/docs/advanced.md#middleware=)!!!

Can't find anything in this article which indicates that `choices` can be an (async) function.
 
> [...] what if I create a middleware to load my choices?!?!!?

I'm not familiar with yargs middleware, but I would be interested to hear if you're able to build something to support this use case!
