### ISSUE TITLE
Setting `limit` on the config with `choices`

### ISSUE THREAD

**Issue by kevinkhill** [hongaar/bandersnatch#404]
I am running into the issue where I want to select from a large list and it puts all the values on screen.

I see in the [enquirer docs that the prop is available](https://www.npmjs.com/package/enquirer#properties=)....

![image](https://user-images.githubusercontent.com/266076/174444408-03abb88f-4f6e-4d8b-bcd8-534c807eee9a.png)

I think we can add the ability to set that, yeah?

**Comment by hongaar** [comment]
Good idea. I prefer to set a hardcoded, sensible value for this option, would that work for you? What value for this option do you think we should choose by default?

**Comment by kevinkhill** [comment]
I prefer even numbers, so 6? 8? Try a few? See what looks most natural to the eye?
