### ISSUE TITLE
`choices` as an array of objects?

### ISSUE THREAD

**Issue by khill-fbmc** [hongaar/bandersnatch#407]
![image](https://user-images.githubusercontent.com/107003416/174804519-6ca3b8bb-be36-4081-b20b-d33b9abac1f3.png)

Is this possible? I am currently showing the user a list like
```
123 - guy
456 - girl
789 - dog
```
and then in my action I am splitting that `.split(" - ")` to get what I need.

Is it possible to hide the ID like in the screenshot? so the user just sees the choices and not the IDs?

**Comment by hongaar** [comment]
Is this possible to do natively with yargs? If yes, then it would be easy to support this scenario, too. Not sure though... If not, this should be added in bandersnatch. I don't have time for it right now, but I'd be happy to review a PR.
