### ISSUE TITLE
Feature Request: Subcommands and Nesting

### ISSUE THREAD

**Issue by khill-fbmc** [hongaar/bandersnatch#626]
First off, love this library, primarily for the REPL features. I keep eyeing [Clipanion](https://github.com/arcanis/clipanion) since it seems like it is designed to be used as a multi-command, nested type of program. I like that, but then I loose my nice REPL features you've added.

This is what I have setup so far, (`match` is from ts-pattern)
<img width="602" alt="image" src="https://github.com/user-attachments/assets/4d2faf88-b89a-41b3-b9fd-688b701901fd">

It works, but does not feel very scalable. Is there a better approach to make nested type commands?

**Comment by hongaar** [comment]
Nested command can be added like this:

```ts
program()
  .add(
    command("session")
      .add(command("start")
        .action(() => console.log("start")
     .add(command("stop")
        .action(() => console.log("stop")
      // and so on...
  )
  .run();
```

Hope this helps.

If you have any ideas how to improve this for your use case, I'm curious to hear!
